# CMake generated Testfile for 
# Source directory: /Users/shane/env_setting/CMake/Tests/ObjC
# Build directory: /Users/shane/env_setting/CMake/Tests/ObjC
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ObjC.simple-build-test]=] "/Users/shane/env_setting/CMake/bin/ctest" "--build-and-test" "/Users/shane/env_setting/CMake/Tests/ObjC/simple-build-test" "/Users/shane/env_setting/CMake/Tests/ObjC/simple-build-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "simple-build-test" "--build-options" "--test-command" "simple-build-test")
set_tests_properties([=[ObjC.simple-build-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLists.txt;9;add_test;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;1;ADD_TEST_MACRO;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;0;")
add_test([=[ObjC.c-file-extension-test]=] "/Users/shane/env_setting/CMake/bin/ctest" "--build-and-test" "/Users/shane/env_setting/CMake/Tests/ObjC/c-file-extension-test" "/Users/shane/env_setting/CMake/Tests/ObjC/c-file-extension-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "c-file-extension-test" "--build-options" "--test-command" "c-file-extension-test")
set_tests_properties([=[ObjC.c-file-extension-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLists.txt;9;add_test;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;2;ADD_TEST_MACRO;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;0;")
add_test([=[ObjC.cxx-file-extension-test]=] "/Users/shane/env_setting/CMake/bin/ctest" "--build-and-test" "/Users/shane/env_setting/CMake/Tests/ObjC/cxx-file-extension-test" "/Users/shane/env_setting/CMake/Tests/ObjC/cxx-file-extension-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "cxx-file-extension-test" "--build-options" "--test-command" "cxx-file-extension-test")
set_tests_properties([=[ObjC.cxx-file-extension-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLists.txt;9;add_test;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;3;ADD_TEST_MACRO;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;0;")
add_test([=[ObjC.objc-file-extension-test]=] "/Users/shane/env_setting/CMake/bin/ctest" "--build-and-test" "/Users/shane/env_setting/CMake/Tests/ObjC/objc-file-extension-test" "/Users/shane/env_setting/CMake/Tests/ObjC/objc-file-extension-test" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "objc-file-extension-test" "--build-options" "--test-command" "objc-file-extension-test")
set_tests_properties([=[ObjC.objc-file-extension-test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLists.txt;9;add_test;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;4;ADD_TEST_MACRO;/Users/shane/env_setting/CMake/Tests/ObjC/CMakeLists.txt;0;")
