# CMake generated Testfile for 
# Source directory: /Users/shane/env_setting/CMake/Tests/CMakeLib
# Build directory: /Users/shane/env_setting/CMake/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMakeLib.testArgumentParser]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testArgumentParser")
set_tests_properties([=[CMakeLib.testArgumentParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestBinPacker]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCTestBinPacker")
set_tests_properties([=[CMakeLib.testCTestBinPacker]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceAllocator]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCTestResourceAllocator")
set_tests_properties([=[CMakeLib.testCTestResourceAllocator]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceSpec]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCTestResourceSpec" "/Users/shane/env_setting/CMake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testCTestResourceSpec]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCTestResourceGroups]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCTestResourceGroups")
set_tests_properties([=[CMakeLib.testCTestResourceGroups]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGccDepfileReader]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testGccDepfileReader" "/Users/shane/env_setting/CMake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testGccDepfileReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testGeneratedFileStream]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testGeneratedFileStream")
set_tests_properties([=[CMakeLib.testGeneratedFileStream]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testJSONHelpers]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testJSONHelpers")
set_tests_properties([=[CMakeLib.testJSONHelpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRST]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testRST" "/Users/shane/env_setting/CMake/Tests/CMakeLib")
set_tests_properties([=[CMakeLib.testRST]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testRange]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testRange")
set_tests_properties([=[CMakeLib.testRange]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testOptional]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testOptional")
set_tests_properties([=[CMakeLib.testOptional]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testString]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testString")
set_tests_properties([=[CMakeLib.testString]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testStringAlgorithms]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testStringAlgorithms")
set_tests_properties([=[CMakeLib.testStringAlgorithms]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testSystemTools]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testSystemTools")
set_tests_properties([=[CMakeLib.testSystemTools]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUTF8]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testUTF8")
set_tests_properties([=[CMakeLib.testUTF8]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLParser]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testXMLParser")
set_tests_properties([=[CMakeLib.testXMLParser]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testXMLSafe]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testXMLSafe")
set_tests_properties([=[CMakeLib.testXMLSafe]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testFindPackageCommand]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testFindPackageCommand")
set_tests_properties([=[CMakeLib.testFindPackageCommand]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVProcessChain]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testUVProcessChain" "/Users/shane/env_setting/CMake/Tests/CMakeLib/testUVProcessChainHelper")
set_tests_properties([=[CMakeLib.testUVProcessChain]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVRAII]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testUVRAII")
set_tests_properties([=[CMakeLib.testUVRAII]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testUVStreambuf]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testUVStreambuf" "/Users/shane/env_setting/CMake/bin/cmake")
set_tests_properties([=[CMakeLib.testUVStreambuf]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtMemory]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCMExtMemory")
set_tests_properties([=[CMakeLib.testCMExtMemory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtAlgorithm]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCMExtAlgorithm")
set_tests_properties([=[CMakeLib.testCMExtAlgorithm]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
add_test([=[CMakeLib.testCMExtEnumSet]=] "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLibTests" "testCMExtEnumSet")
set_tests_properties([=[CMakeLib.testCMExtEnumSet]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;67;add_test;/Users/shane/env_setting/CMake/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
